source 'file:///Users/jakub/Applied-Recognition/CocoaPods-repo'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'Face Capture Demo' do
  # use_frameworks!

  # Pods for Face Capture Demo
  pod 'FaceCapture', :path => '../'
  pod 'SpoofDeviceDetection/Model', '~> 1.0'
  pod 'FaceDetectionMediaPipe', :git => 'https://github.com/AppliedRecognition/Face-Detection-MediaPipe-Apple.git', :commit => 'b2b35717b8523d3a03e9b688db5b0e61fc1ca8e1'
end
